filter:
    excluded_paths:
        - "docs/"
        - "*/views/*"
        - "*/*.blade.php"
        - "*/FontAwesome.php"
        - "src/assets/"
        - "src/configs/"
        - "src/database/"
        - "*/localization/*"
        - "*/Seeder.php"
        - "*/*_routes.php"
        - "*/*Form.php"
        - "src/laravel-filemanager/"
        - "*/*.js"
        - "*/*.MD"